/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/auth/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getAuthStatus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["logout"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getProfile"];
        put: operations["updateProfile"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/forgot-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["forgotPassword"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/verify-reset-token": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["verifyResetToken"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/reset-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["resetPassword"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/organizations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listOrganizations"];
        put?: never;
        post: operations["createOrganization"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/organizations/join": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["joinOrganization"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/organizations/{orgId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orgId: components["parameters"]["OrgId"];
            };
            cookie?: never;
        };
        get: operations["getOrganization"];
        put?: never;
        post?: never;
        delete: operations["deleteOrganization"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/organizations/{orgId}/members": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orgId: components["parameters"]["OrgId"];
            };
            cookie?: never;
        };
        get: operations["listOrganizationMembers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/organizations/{orgId}/teams": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orgId: components["parameters"]["OrgId"];
            };
            cookie?: never;
        };
        get: operations["listOrganizationTeams"];
        put?: never;
        post: operations["createTeam"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/organizations/{orgId}/projects": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orgId: components["parameters"]["OrgId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["createProject"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/teams/{teamId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                teamId: components["parameters"]["TeamId"];
            };
            cookie?: never;
        };
        get: operations["getTeam"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/teams/{teamId}/join": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                teamId: components["parameters"]["TeamId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["joinTeam"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/teams/{teamId}/leave": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                teamId: components["parameters"]["TeamId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["leaveTeam"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/teams/{teamId}/members": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                teamId: components["parameters"]["TeamId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["addTeamMember"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{projectId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectId"];
            };
            cookie?: never;
        };
        get: operations["getProject"];
        put: operations["updateProject"];
        post?: never;
        delete: operations["deleteProject"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{projectId}/feishu-bot": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectId"];
            };
            cookie?: never;
        };
        get: operations["getProjectFeishuBot"];
        put: operations["updateProjectFeishuBot"];
        post?: never;
        delete: operations["deleteProjectFeishuBot"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{projectId}/feishu-bot/test": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["testProjectFeishuBot"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{projectId}/sprints": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["createSprint"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{projectId}/board": {
        parameters: {
            query?: {
                sprint_id?: number;
            };
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectId"];
            };
            cookie?: never;
        };
        get: operations["getBoard"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{projectId}/requirements": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectId"];
            };
            cookie?: never;
        };
        get: operations["listRequirements"];
        put?: never;
        post: operations["createRequirement"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{projectId}/requirements/stats": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectId"];
            };
            cookie?: never;
        };
        get: operations["getRequirementStats"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{projectId}/requirements/batch-delete": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["batchDeleteRequirements"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{projectId}/requirements/batch-bind-sprint": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["batchBindRequirementsToSprint"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{projectId}/issues": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["createIssue"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{projectId}/bugs": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectId"];
            };
            cookie?: never;
        };
        get: operations["listBugs"];
        put?: never;
        post: operations["createBug"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{projectId}/bugs/stats": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectId"];
            };
            cookie?: never;
        };
        get: operations["getBugStats"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sprints/{sprintId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sprintId: components["parameters"]["SprintId"];
            };
            cookie?: never;
        };
        get: operations["getSprint"];
        put: operations["updateSprint"];
        post?: never;
        delete: operations["deleteSprint"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sprints/{sprintId}/worklogs": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sprintId: components["parameters"]["SprintId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["createSprintWorklog"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sprints/{sprintId}/requirements": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sprintId: components["parameters"]["SprintId"];
            };
            cookie?: never;
        };
        get: operations["listSprintRequirements"];
        put: operations["updateSprintRequirements"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/requirements/{requirementId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                requirementId: components["parameters"]["RequirementId"];
            };
            cookie?: never;
        };
        get: operations["getRequirement"];
        put: operations["updateRequirement"];
        post?: never;
        delete: operations["deleteRequirement"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/issues/{issueId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                issueId: components["parameters"]["IssueId"];
            };
            cookie?: never;
        };
        get: operations["getIssue"];
        put: operations["updateIssue"];
        post?: never;
        delete: operations["deleteIssue"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/issues/{issueId}/worklogs": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                issueId: components["parameters"]["IssueId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["createIssueWorklog"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/issues/{issueId}/worklogs/{worklogId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                issueId: components["parameters"]["IssueId"];
                worklogId: components["parameters"]["WorklogId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["deleteIssueWorklog"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/issues/{issueId}/move": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                issueId: components["parameters"]["IssueId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["moveIssue"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/issues/{issueId}/assign_sprint": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                issueId: components["parameters"]["IssueId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["assignIssueSprint"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/bugs/{bugId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                bugId: components["parameters"]["BugId"];
            };
            cookie?: never;
        };
        get: operations["getBug"];
        put: operations["updateBug"];
        post?: never;
        delete: operations["deleteBug"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/bugs/{bugId}/evidences": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                bugId: components["parameters"]["BugId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["createBugEvidence"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/bugs/{bugId}/worklogs": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                bugId: components["parameters"]["BugId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["createBugWorklog"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/bugs/{bugId}/worklogs/{worklogId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                bugId: components["parameters"]["BugId"];
                worklogId: components["parameters"]["WorklogId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["deleteBugWorklog"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/uploads/markdown-images": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["uploadMarkdownImages"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listUsers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/workbench": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getWorkbench"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        AuthStatus: {
            authenticated: boolean;
            user?: components["schemas"]["User"];
        };
        User: {
            id: number;
            username: string;
            /** Format: email */
            email: string;
            role?: string | null;
        };
        Organization: {
            id: number;
            name: string;
            owner_id: number;
            owner_name?: string | null;
            projects_count?: number;
            done_issues_count?: number;
        };
        Team: {
            id: number;
            name: string;
            description?: string;
            organization_id: number;
            members_count?: number;
        };
        Project: {
            id: number;
            name: string;
            description?: string | null;
            organization_id: number;
            team_id?: number | null;
            team_name?: string | null;
            feishu_bot_configured?: boolean;
        };
        FeishuBotStatus: {
            enabled: boolean;
            webhook_masked?: string | null;
            secret_configured: boolean;
        };
        Sprint: {
            id: number;
            name: string;
            /** @enum {string} */
            status: "open" | "active" | "closed";
            project_id: number;
            /** Format: date */
            start_date?: string | null;
            /** Format: date */
            end_date?: string | null;
            progress?: number;
            time_spent?: number;
        };
        Requirement: {
            id: number;
            title: string;
            content: string;
            priority: number;
            /** @enum {string} */
            status: "pending" | "in_progress" | "testing" | "completed";
            project_id: number;
            sprint_id?: number | null;
            /** Format: date */
            expected_delivery_date?: string | null;
        };
        Issue: {
            id: number;
            item_code?: string | null;
            title: string;
            description?: string | null;
            /** @enum {string} */
            status: "todo" | "doing" | "done";
            priority: number;
            project_id: number;
            sprint_id?: number | null;
            requirement_id?: number | null;
            assignee_id?: number | null;
            time_estimate?: number;
            time_spent?: number;
        };
        Bug: {
            id: number;
            item_code?: string | null;
            title: string;
            description: string;
            severity: number;
            /** @enum {string} */
            status: "open" | "in_progress" | "fixed" | "resolved" | "closed" | "rejected";
            project_id: number;
            sprint_id?: number | null;
            requirement_id?: number | null;
            assignee_id?: number | null;
            evidence_count?: number;
            time_estimate?: number;
            time_spent?: number;
            /** @enum {string} */
            bug_type?: "functional" | "performance" | "api" | "security" | "ui" | "compatibility" | "usability" | "config" | "data" | "requirement";
            /** @enum {string} */
            priority?: "critical" | "high" | "normal" | "low" | "lowest";
            /** @enum {string} */
            platform?: "server" | "h5" | "android" | "ios" | "harmony" | "pc_web";
            /** @enum {string} */
            discovery_phase?: "smoke" | "round_1" | "round_2" | "regression" | "acceptance" | "integration" | "gray" | "production";
            /** @enum {string|null} */
            discovery_channel?: "user_feedback" | "monitoring" | "log" | "sprint" | null;
        };
    };
    responses: never;
    parameters: {
        OrgId: number;
        TeamId: number;
        ProjectId: number;
        SprintId: number;
        RequirementId: number;
        IssueId: number;
        BugId: number;
        WorklogId: number;
        Search: string;
        Status: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getAuthStatus: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 当前会话状态 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthStatus"];
                };
            };
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    [key: string]: unknown;
                };
            };
        };
        responses: {
            /** @description 请求成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    register: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    [key: string]: unknown;
                };
            };
        };
        responses: {
            /** @description 请求成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 请求成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    getProfile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 请求成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    updateProfile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    [key: string]: unknown;
                };
            };
        };
        responses: {
            /** @description 请求成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    forgotPassword: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    [key: string]: unknown;
                };
            };
        };
        responses: {
            /** @description 请求成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    verifyResetToken: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    [key: string]: unknown;
                };
            };
        };
        responses: {
            /** @description 请求成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    resetPassword: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    [key: string]: unknown;
                };
            };
        };
        responses: {
            /** @description 请求成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    listOrganizations: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 组织列表 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Organization"][];
                };
            };
        };
    };
    createOrganization: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    [key: string]: unknown;
                };
            };
        };
        responses: {
            /** @description 创建成功 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    joinOrganization: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    [key: string]: unknown;
                };
            };
        };
        responses: {
            /** @description 请求成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    getOrganization: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orgId: components["parameters"]["OrgId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 请求成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    deleteOrganization: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orgId: components["parameters"]["OrgId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 请求成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    listOrganizationMembers: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orgId: components["parameters"]["OrgId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 请求成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    listOrganizationTeams: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orgId: components["parameters"]["OrgId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 请求成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    createTeam: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orgId: components["parameters"]["OrgId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    [key: string]: unknown;
                };
            };
        };
        responses: {
            /** @description 创建成功 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    createProject: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orgId: components["parameters"]["OrgId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    [key: string]: unknown;
                };
            };
        };
        responses: {
            /** @description 创建成功 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    getTeam: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                teamId: components["parameters"]["TeamId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 请求成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    joinTeam: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                teamId: components["parameters"]["TeamId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 请求成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    leaveTeam: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                teamId: components["parameters"]["TeamId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 请求成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    addTeamMember: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                teamId: components["parameters"]["TeamId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    [key: string]: unknown;
                };
            };
        };
        responses: {
            /** @description 请求成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    getProject: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 请求成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    updateProject: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    [key: string]: unknown;
                };
            };
        };
        responses: {
            /** @description 请求成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    deleteProject: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 请求成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    getProjectFeishuBot: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 飞书机器人脱敏状态 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeishuBotStatus"];
                };
            };
        };
    };
    updateProjectFeishuBot: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    webhook_url?: string;
                    secret?: string;
                };
            };
        };
        responses: {
            /** @description 飞书机器人脱敏状态 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeishuBotStatus"];
                };
            };
        };
    };
    deleteProjectFeishuBot: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 请求成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    testProjectFeishuBot: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 请求成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    createSprint: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    [key: string]: unknown;
                };
            };
        };
        responses: {
            /** @description 创建成功 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    getBoard: {
        parameters: {
            query?: {
                sprint_id?: number;
            };
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 请求成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    listRequirements: {
        parameters: {
            query?: {
                search?: components["parameters"]["Search"];
                status?: components["parameters"]["Status"];
                priority?: number;
            };
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 需求列表 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Requirement"][];
                };
            };
        };
    };
    createRequirement: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    [key: string]: unknown;
                };
            };
        };
        responses: {
            /** @description 创建成功 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    getRequirementStats: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 请求成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    batchDeleteRequirements: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    requirement_ids: number[];
                };
            };
        };
        responses: {
            /** @description 批量删除结果 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        success: boolean;
                        deleted_count: number;
                        deleted_issue_count: number;
                    };
                };
            };
        };
    };
    batchBindRequirementsToSprint: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    requirement_ids: number[];
                    sprint_id: number;
                };
            };
        };
        responses: {
            /** @description 批量绑定结果 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        success: boolean;
                        updated_count: number;
                        sprint: components["schemas"]["Sprint"];
                    };
                };
            };
        };
    };
    createIssue: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    [key: string]: unknown;
                };
            };
        };
        responses: {
            /** @description 创建成功 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    listBugs: {
        parameters: {
            query?: {
                search?: components["parameters"]["Search"];
                status?: components["parameters"]["Status"];
                severity?: number;
                assignee_id?: number | "unassigned";
            };
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 缺陷列表 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Bug"][];
                };
            };
        };
    };
    createBug: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    [key: string]: unknown;
                };
            };
        };
        responses: {
            /** @description 创建成功 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    getBugStats: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 请求成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    getSprint: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sprintId: components["parameters"]["SprintId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 请求成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    updateSprint: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sprintId: components["parameters"]["SprintId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    [key: string]: unknown;
                };
            };
        };
        responses: {
            /** @description 请求成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    deleteSprint: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sprintId: components["parameters"]["SprintId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 请求成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    createSprintWorklog: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sprintId: components["parameters"]["SprintId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    [key: string]: unknown;
                };
            };
        };
        responses: {
            /** @description 创建成功 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    listSprintRequirements: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sprintId: components["parameters"]["SprintId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 请求成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    updateSprintRequirements: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sprintId: components["parameters"]["SprintId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    requirement_ids: number[];
                    /** @default false */
                    delete_unbound_tasks?: boolean;
                };
            };
        };
        responses: {
            /** @description 迭代需求关联更新结果 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        sprint: components["schemas"]["Sprint"];
                        requirements: components["schemas"]["Requirement"][];
                        deleted_issue_count: number;
                    };
                };
            };
        };
    };
    getRequirement: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                requirementId: components["parameters"]["RequirementId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 请求成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    updateRequirement: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                requirementId: components["parameters"]["RequirementId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    [key: string]: unknown;
                };
            };
        };
        responses: {
            /** @description 请求成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    deleteRequirement: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                requirementId: components["parameters"]["RequirementId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 请求成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    getIssue: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                issueId: components["parameters"]["IssueId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 请求成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    updateIssue: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                issueId: components["parameters"]["IssueId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    [key: string]: unknown;
                };
            };
        };
        responses: {
            /** @description 请求成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    deleteIssue: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                issueId: components["parameters"]["IssueId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 请求成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    createIssueWorklog: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                issueId: components["parameters"]["IssueId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    [key: string]: unknown;
                };
            };
        };
        responses: {
            /** @description 创建成功 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    deleteIssueWorklog: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                issueId: components["parameters"]["IssueId"];
                worklogId: components["parameters"]["WorklogId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 请求成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    moveIssue: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                issueId: components["parameters"]["IssueId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    [key: string]: unknown;
                };
            };
        };
        responses: {
            /** @description 请求成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    assignIssueSprint: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                issueId: components["parameters"]["IssueId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    [key: string]: unknown;
                };
            };
        };
        responses: {
            /** @description 请求成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    getBug: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                bugId: components["parameters"]["BugId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 请求成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    updateBug: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                bugId: components["parameters"]["BugId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    [key: string]: unknown;
                };
            };
        };
        responses: {
            /** @description 请求成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    deleteBug: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                bugId: components["parameters"]["BugId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 请求成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    createBugEvidence: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                bugId: components["parameters"]["BugId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": {
                    comment?: string;
                    stack_trace?: string;
                    screenshots?: string[];
                };
            };
        };
        responses: {
            /** @description 创建成功 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    createBugWorklog: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                bugId: components["parameters"]["BugId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    [key: string]: unknown;
                };
            };
        };
        responses: {
            /** @description 创建成功 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    deleteBugWorklog: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                bugId: components["parameters"]["BugId"];
                worklogId: components["parameters"]["WorklogId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 请求成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    uploadMarkdownImages: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": {
                    images: string[];
                };
            };
        };
        responses: {
            /** @description 图片上传成功 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        urls: string[];
                    };
                };
            };
        };
    };
    listUsers: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 用户列表 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"][];
                };
            };
        };
    };
    getWorkbench: {
        parameters: {
            query?: {
                start_date?: string;
                end_date?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 请求成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
}
